# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/work/cpu4teamwork/cpu/cpu.runs/synth_1/UART_Top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
set_param pwropt.maxFaninFanoutToNetRatio 5000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/work/cpu4teamwork/cpu/cpu.cache/wt [current_project]
set_property parent.project_path D:/work/cpu4teamwork/cpu/cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/work/cpu4teamwork/cpu/cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  D:/work/cpu4teamwork/AllFiles/ALU.v
  D:/work/cpu4teamwork/AllFiles/ALU_float.v
  D:/work/cpu4teamwork/AllFiles/Adder.v
  D:/work/cpu4teamwork/AllFiles/DFF.v
  D:/work/cpu4teamwork/AllFiles/Data_Receiver.v
  D:/work/cpu4teamwork/AllFiles/EPCStack.v
  D:/work/cpu4teamwork/AllFiles/FRegfile.v
  D:/work/cpu4teamwork/AllFiles/IM_ROM.v
  D:/work/cpu4teamwork/AllFiles/INTR_handler.v
  D:/work/cpu4teamwork/AllFiles/INTStack.v
  D:/work/cpu4teamwork/AllFiles/MEM_COMBINES.v
  D:/work/cpu4teamwork/AllFiles/Multiplier.v
  D:/work/cpu4teamwork/AllFiles/PC_Register.v
  D:/work/cpu4teamwork/AllFiles/Regifile.v
  D:/work/cpu4teamwork/AllFiles/Subber.v
  D:/work/cpu4teamwork/AllFiles/UART_Receiver.v
  D:/work/cpu4teamwork/AllFiles/UART_Transmitter.v
  D:/work/cpu4teamwork/AllFiles/_7Seg_Driver_Choice.v
  D:/work/cpu4teamwork/AllFiles/addition_normaliser.v
  D:/work/cpu4teamwork/AllFiles/check_type.v
  D:/work/cpu4teamwork/AllFiles/clr_generator.v
  D:/work/cpu4teamwork/AllFiles/controller_with_float.v
  D:/work/cpu4teamwork/AllFiles/counter.v
  D:/work/cpu4teamwork/AllFiles/decoder_38.v
  D:/work/cpu4teamwork/AllFiles/divider.v
  D:/work/cpu4teamwork/AllFiles/float_to_i.v
  D:/work/cpu4teamwork/AllFiles/get_negative.v
  D:/work/cpu4teamwork/AllFiles/get_num_for_sb.v
  D:/work/cpu4teamwork/AllFiles/get_num_for_sh.v
  D:/work/cpu4teamwork/AllFiles/get_poscount.v
  D:/work/cpu4teamwork/AllFiles/get_positive.v
  D:/work/cpu4teamwork/AllFiles/get_positive_for_ui.v
  D:/work/cpu4teamwork/AllFiles/get_precount.v
  D:/work/cpu4teamwork/AllFiles/hardware_controller_with_float.v
  D:/work/cpu4teamwork/AllFiles/i_to_float.v
  D:/work/cpu4teamwork/AllFiles/logical_left.v
  D:/work/cpu4teamwork/AllFiles/mux_21.v
  D:/work/cpu4teamwork/AllFiles/mux_41.v
  D:/work/cpu4teamwork/AllFiles/pattern.v
  D:/work/cpu4teamwork/AllFiles/priority_Encoder.v
  D:/work/cpu4teamwork/AllFiles/register.v
  D:/work/cpu4teamwork/AllFiles/riscv_datapath_with_float.v
  D:/work/cpu4teamwork/AllFiles/seg7.v
  D:/work/cpu4teamwork/AllFiles/sign_extender.v
  D:/work/cpu4teamwork/AllFiles/signals_with_float.v
  D:/work/cpu4teamwork/AllFiles/ui_to_float.v
  D:/work/cpu4teamwork/AllFiles/zero_extender.v
  D:/work/cpu4teamwork/AllFiles/UART_Top.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/work/cpu4teamwork/AllFiles/UART.xdc
set_property used_in_implementation false [get_files D:/work/cpu4teamwork/AllFiles/UART.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/work/cpu4teamwork/cpu/cpu.srcs/utils_1/imports/synth_1/UART_Top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top UART_Top -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef UART_Top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file UART_Top_utilization_synth.rpt -pb UART_Top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
